---
abstract: 'make HTML5 DOM trees less insane'
author:
  - 'Toby Inkster <tobyink@cpan.org>'
  - 'TOBYINK <tobyink@cpan.org>'
build_requires:
  Test::More: '0.61'
  XML::LibXML::Debugging: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.17'
dynamic_config: 0
generated_by: 'Dist::Inkt::Profile::TOBYINK version 0.016, CPAN::Meta::Converter version 2.140640'
keywords:
  - Attributes
  - DOM
  - Fix
  - Fixer
  - HTML
  - HTML5
  - Lang
  - Language
  - Markup
  - Namespaces
  - XML
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: HTML-HTML5-Sanity
no_index:
  directory:
    - eg
    - examples
    - inc
    - t
    - xt
optional_features: {}
provides:
  HTML::HTML5::Sanity:
    file: lib/HTML/HTML5/Sanity.pm
    version: '0.105'
recommends:
  HTML::HTML5::Parser: '0.107'
requires:
  Locale::Country: '0'
  XML::LibXML: '1.70'
resources:
  X_identifier: http://purl.org/NET/cpan-uri/dist/HTML-HTML5-Sanity/project
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=HTML-HTML5-Sanity
  homepage: https://metacpan.org/release/HTML-HTML5-Sanity
  license: http://dev.perl.org/licenses/
  repository: git://github.com/tobyink/p5-html-html5-sanity.git
version: '0.105'
