---
abstract: 'make HTML5 DOM trees less insane'
author:
  - 'Toby Inkster <tobyink@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0.61
  XML::LibXML::Debugging: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 0
generated_by: 'Module::Install version 1.06'
keywords:
  - Attributes
  - DOM
  - Fix
  - Fixer
  - HTML
  - HTML5
  - Lang
  - Language
  - Markup
  - Namespaces
  - XML
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: HTML::HTML5::Sanity
name: HTML-HTML5-Sanity
no_index:
  directory:
    - inc
    - t
    - xt
recommends:
  HTML::HTML5::Parser: 0.107
requires:
  Locale::Country: 0
  Object::AUTHORITY: 0
  XML::LibXML: 1.70
  perl: 5.10.0
resources:
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=HTML-HTML5-Sanity
  homepage: https://metacpan.org/release/HTML-HTML5-Sanity
  license: http://dev.perl.org/licenses/
  repository: https://github.com/tobyink/p5-html-html5-sanity
version: 0.104
